import { Link } from 'react-router-dom';
import { Bot, ArrowLeft } from 'lucide-react';

export default function Terms() {
  return (
    <div style={{ minHeight: '100vh', background: '#0a0a0f' }}>
      <header style={{ height: 56, borderBottom: '0.5px solid #1e2a3a', background: 'rgba(10,10,15,0.95)', display: 'flex', alignItems: 'center', padding: '0 24px', position: 'sticky', top: 0, zIndex: 40 }}>
        <div style={{ maxWidth: 760, margin: '0 auto', width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Link to="/" style={{ display: 'flex', alignItems: 'center', gap: 8, textDecoration: 'none' }}>
            <div style={{ width: 30, height: 30, borderRadius: 8, background: '#2563eb', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <Bot size={16} color="#fff" />
            </div>
            <span style={{ fontSize: 15, fontWeight: 700, color: '#fff' }}>Desklo</span>
          </Link>
          <Link to="/" style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 13, color: '#8899aa', textDecoration: 'none' }}>
            <ArrowLeft size={14} /> Back home
          </Link>
        </div>
      </header>

      <div style={{ maxWidth: 760, margin: '0 auto', padding: '48px 24px', color: '#cdd9e8', lineHeight: 1.7, fontSize: 14 }}>
        <h1 style={{ fontSize: 28, fontWeight: 700, color: '#fff', marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ fontSize: 12, color: '#8899aa', marginBottom: 32 }}>Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

        <Section title="1. Agreement to Terms">
          By accessing or using Desklo ("Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
        </Section>

        <Section title="2. Description of Service">
          Desklo provides an AI-powered chat widget that businesses can embed on their websites to answer customer questions, capture leads, and provide 24/7 automated customer support.
        </Section>

        <Section title="3. Account Registration">
          You must provide accurate information when creating an account. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.
        </Section>

        <Section title="4. Subscription and Payment">
          Desklo is offered on a subscription basis at the price displayed at signup (currently $99/month). Subscriptions automatically renew each billing cycle unless cancelled. You may cancel at any time through your account settings; cancellation takes effect at the end of the current billing period. We do not offer refunds for partial billing periods unless required by law.
        </Section>

        <Section title="5. Acceptable Use">
          You agree not to use Desklo to: violate any law or regulation, transmit harmful, abusive, or fraudulent content, attempt to interfere with or disrupt the Service's infrastructure, or use the AI receptionist to impersonate a real human without disclosure where required by law.
        </Section>

        <Section title="6. AI-Generated Content Disclaimer">
          Desklo's chat responses are generated by an AI language model based on the business information you provide. While we strive for accuracy, AI-generated responses may occasionally be incorrect or incomplete. You are responsible for reviewing your business information for accuracy and for monitoring conversations. Desklo is not liable for any decisions made by your customers based on AI-generated responses.
        </Section>

        <Section title="7. Your Content">
          You retain ownership of the business information you provide. By using Desklo, you grant us a license to use that information solely to operate and provide the Service to you.
        </Section>

        <Section title="8. Service Availability">
          We strive to maintain high uptime but do not guarantee uninterrupted access to the Service. We are not liable for downtime caused by third-party providers, maintenance, or circumstances outside our reasonable control.
        </Section>

        <Section title="9. Termination">
          We reserve the right to suspend or terminate your account if you violate these Terms. You may terminate your account at any time by contacting us or using the account deletion option in Settings.
        </Section>

        <Section title="10. Limitation of Liability">
          To the maximum extent permitted by law, Desklo and its operators shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service, including lost business, lost revenue, or lost data.
        </Section>

        <Section title="11. Changes to These Terms">
          We may update these Terms from time to time. Continued use of the Service after changes take effect constitutes acceptance of the revised Terms.
        </Section>

        <Section title="12. Contact Us">
          Questions about these Terms can be directed to{' '}
          <a href="mailto:desklosupport@gmail.com" style={{ color: '#60a5fa' }}>desklosupport@gmail.com</a>.
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <h2 style={{ fontSize: 16, fontWeight: 600, color: '#fff', marginBottom: 10 }}>{title}</h2>
      <p style={{ color: '#8899aa' }}>{children}</p>
    </div>
  );
}